try {
  console.log("Start of try runs");
  console.log("end of try");
} catch (err) {
  console.log("Error has occured", err);
} finally {
  console.log("Finally always runs");
}
